In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [6]:
df=pd.read_csv(r"C:\Users\Usman\Downloads\page2\carprices.csv")

In [7]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [10]:
a=pd.get_dummies(df[["Car Model"]])
a

Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class
0                   0                 1                                0
1                   0                 1                                0
2                   0                 1                                0
3                   0                 1                                0
4                   0                 1                                0
5                   1                 0                                0
6                   1                 0                                0
7                   1                 0                                0
8                   1                 0                                0
9                   0                 0                                1
10                  0                 0                                1
11                  0                 0                                1
12                  0                 0                                1

In [12]:
merge=pd.concat([df,a],axis=1)
merge

Car Model  Mileage  Sell Price($)  Age(yrs)  \
0                  BMW X5    69000          18000         6   
1                  BMW X5    35000          34000         3   
2                  BMW X5    57000          26100         5   
3                  BMW X5    22500          40000         2   
4                  BMW X5    46000          31500         4   
5                 Audi A5    59000          29400         5   
6                 Audi A5    52000          32000         5   
7                 Audi A5    72000          19300         6   
8                 Audi A5    91000          12000         8   
9   Mercedez Benz C class    67000          22000         6   
10  Mercedez Benz C class    83000          20000         7   
11  Mercedez Benz C class    79000          21000         7   
12  Mercedez Benz C class    59000          33000         5   

    Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class  
0                   0                 1                                0  
1                   0                 1                                0  
2                   0                 1                                0  
3                   0                 1                                0  
4                   0                 1                                0  
5                   1                 0                                0  
6                   1                 0                                0  
7                   1                 0                                0  
8                   1                 0                                0  
9                   0                 0                                1  
10                  0                 0                                1  
11                  0                 0                                1  
12                  0                 0                                1

In [15]:
finaldf=merge.drop(["Car Model_Mercedez Benz C class","Car Model"],axis=1)
finaldf

Mileage  Sell Price($)  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000          18000         6                  0                 1
1     35000          34000         3                  0                 1
2     57000          26100         5                  0                 1
3     22500          40000         2                  0                 1
4     46000          31500         4                  0                 1
5     59000          29400         5                  1                 0
6     52000          32000         5                  1                 0
7     72000          19300         6                  1                 0
8     91000          12000         8                  1                 0
9     67000          22000         6                  0                 0
10    83000          20000         7                  0                 0
11    79000          21000         7                  0                 0
12    59000          33000         5                  0                 0

In [16]:
reg=LinearRegression()

In [22]:
X=finaldf.drop(["Sell Price($)"],axis=1)
X

Mileage  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000         6                  0                 1
1     35000         3                  0                 1
2     57000         5                  0                 1
3     22500         2                  0                 1
4     46000         4                  0                 1
5     59000         5                  1                 0
6     52000         5                  1                 0
7     72000         6                  1                 0
8     91000         8                  1                 0
9     67000         6                  0                 0
10    83000         7                  0                 0
11    79000         7                  0                 0
12    59000         5                  0                 0

In [25]:
y=finaldf[["Sell Price($)"]]
y

Sell Price($)
0           18000
1           34000
2           26100
3           40000
4           31500
5           29400
6           32000
7           19300
8           12000
9           22000
10          20000
11          21000
12          33000

In [26]:
reg.fit(X,y)

LinearRegression()

In [27]:
reg.predict([[45000,4,0,0]])

array([[36991.31721061]])

In [28]:
reg.predict([[86000,7,0,1]])

array([[11080.74313219]])

In [29]:
reg.score(X,y)

0.9417050937281083

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
le=LabelEncoder()

In [33]:
Newdf=le.fit_transform(df["Car Model"])

In [34]:
Newdf

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])